#!/bin/bash

set -euo pipefail

say() {
	echo -e "$(date -Isec -u): ${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

[ -v BASE_DIR ] || BASE_DIR="/app"
[ -v NEO4J_HOME ] || NEO4J_HOME="${BASE_DIR}/neo4j"
[ -v NEO4J_CONF ] || NEO4J_CONF="${BASE_DIR}/conf"

# Run the launcher, which returns immediately
say "Launching Neo4J..."
exec /usr/share/neo4j/bin/neo4j console --expand-commands
