#!/bin/bash

set -euo pipefail
. /.functions

set_or_default BASE_DIR "/app"
set_or_default DATA_DIR "${BASE_DIR}/data"
set_or_default NEO4J_HOME "${BASE_DIR}/neo4j"
set_or_default NEO4J_CONF "${BASE_DIR}/conf"

#
# Init SSL certificates and trusts
#
init_ssl

# Are the databases already initialized?
DBS="$(find "${DATA_DIR}" -type f -name '*.db' | wc -l)"

if [ -v NEO4J_ADMIN_PASSWORD ] && [ -n "${NEO4J_ADMIN_PASSWORD}" ] && [ ${DBS} -eq 0 ] ; then
	# We only do this on the first boot ...
	say "Setting the admin password..."
	neo4j-admin set-initial-password "${NEO4J_ADMIN_PASSWORD}"
fi

execute /usr/share/neo4j/bin/neo4j console --expand-commands
